#ifndef QTLIBRARYDEMO_GLOBAL_H
#define QTLIBRARYDEMO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTLIBRARYDEMO_LIBRARY)
#  define QTLIBRARYDEMO_EXPORT Q_DECL_EXPORT
#else
#  define QTLIBRARYDEMO_EXPORT Q_DECL_IMPORT
#endif

#endif // QTLIBRARYDEMO_GLOBAL_H
